language: node_js
node_js:
  - stable

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
 - yarn clean

install:
  - yarn
  - yarn global add codecov

script:
  - yarn test
  # - yarn run coverage
  # - yarn run check-coverage
  # - codecov --token=$CODECOV_TOKEN
  # - codecov -f api/coverage/*.json

after_success:
#  - export CODECOV_TOKEN
#  - bash <(curl -s https://codecov.io/bash)

after_script:
  - yarn run report-coverage