language: node_js
node_js:
  - "10"

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
 - npm prune

before_install:
 - docker-compose up

install:
  - npm install -g nyc coveralls codecov

# script:
  # - npm run coverage
  # - npm run check-coverage
  # - codecov --token=$CODECOV_TOKEN
  # - codecov -f api/coverage/*.json

# after_success:
#  - export CODECOV_TOKEN
#  - bash <(curl -s https://codecov.io/bash)
#  - codecov --token=:token

# after_script:
  # - npm run report-coverage