version: '3'
services:
  db:
    container_name: MemoireDB
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=memoire_admin
      - POSTGRES_PASSWORD=memo543ire
      - POSTGRES_DB=memoire_db
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql
  api:
    image: krizten/memoire-api
    container_name: MemoireAPI
    restart: always
    environment:
      - NODE_ENV=development
    build: .
    volumes:
      - "./:/usr/src/app"
    ports:
      - "8500:8500"
    depends_on:
      - "db"
    command: sh -c './wait-for-pg.sh db:5432 -- npm run start:dev'